name: Examples Check

on:
  schedule:
    - cron: "0 16 * * *" 
  workflow_dispatch:
  push:
    branches:
      - test-workflows     
  pull_request:
    branches:
      - main

jobs:
  run-java-example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      HEDERA_NETWORK: local
      MIRROR_NODE_URL: http://localhost:5551/api/v1
      STATUS_DIR: .github/example-status
      STATUS_FILE: .github/example-status/java-status.md

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Solo
        id: solo
        uses: hiero-ledger/hiero-solo-action@v0.11.0
        with:
          installMirrorNode: true

      - name: Show assigned account
        run: |
          echo "ECDSA Account: ${{ steps.solo.outputs.ecdsaAccountId }}"
          echo "ECDSA PrivateKey: **** (redacted)"

      - name: Wait for Mirror Node health
        env:
          URL: ${{ env.MIRROR_NODE_URL }}  
        run: |
          set -euo pipefail
          base="${URL%/}"             # strip trailing slash
          root="${base%/api/v1}"      # strip /api/v1 if present
          # Try both /api/v1/health and /health (some builds expose both)
          tries=60
          echo "Waiting for mirror health at: ${base}/health (or ${root}/health)"
          for i in $(seq 1 $tries); do
            if curl -fsS "${base}/health" >/dev/null 2>&1 || curl -fsS "${root}/health" >/dev/null 2>&1; then
              echo "✅ Mirror health OK"
              exit 0
            fi
            echo "⏳ Mirror not ready (try $i/${tries})…"
            sleep 2
          done
          echo "❌ Mirror never became healthy"
          curl -sv "${base}/health" || curl -sv "${root}/health" || true
          exit 1

      - name: Sanity check mirror endpoints
        env:
          URL: ${{ env.MIRROR_NODE_URL }}
        run: |
          set -euo pipefail
          base="${URL%/}"
          echo "GET ${base}/network/nodes?limit=1"
          curl -fsS "${base}/network/nodes?limit=1" | jq -C . || true
          echo "GET ${base}/accounts?limit=1"
          curl -fsS "${base}/accounts?limit=1" | jq -C . || true


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Bootstrap Gradle for examples/java
        run: |
          pwd
          chmod +x ./.github/scripts/java-gradle-bootstrap.sh
          ./.github/scripts/java-gradle-bootstrap.sh

      - name: Build & Run Java example
        id: run_java
        env:
          OPERATOR_ID: ${{ steps.solo.outputs.ecdsaAccountId }}
          OPERATOR_KEY: ${{ steps.solo.outputs.ecdsaPrivateKey }}
          HEDERA_NETWORK: ${{ env.HEDERA_NETWORK }}
          MIRROR_NODE_URL: ${{ env.MIRROR_NODE_URL }}
        run: |
          chmod +x ./.github/scripts/run-java.sh
          ./.github/scripts/run-java.sh

      - name: Summarize status
        if: ${{ always() }}
        run: |
          mkdir -p "$STATUS_DIR"
          ts="$(date -u +'%Y-%m-%d %H:%M:%SZ')"
          {
            if [ "${{ steps.run_java.outcome }}" = "success" ]; then
              echo "## ✅ Java example passed"
            else
              echo "## ❌ Java example failed"
            fi
            echo "- Timestamp (UTC): ${ts}"
            echo "- Network: ${HEDERA_NETWORK}"
            echo ""
            echo "<details><summary>Output</summary>"
            if [ -f java-output.txt ]; then
              # Redact the private key if script exists; otherwise print raw output
              if [ -f ./.github/scripts/redact.sh ]; then
                bash ./.github/scripts/redact.sh "${{ steps.solo.outputs.ecdsaPrivateKey }}" java-output.txt || cat java-output.txt
              else
                cat java-output.txt
              fi
            else
              echo "_No output captured._"
            fi
            echo "</details>"
          } > "$STATUS_FILE"

      - name: Open/Update PR with status
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update example run status"
          signoff: true 
          title: "chore: example run status"
          body: "Automated run of examples"
          branch: "bot/java-example-check"
          add-paths: ${{ env.STATUS_FILE }}
          labels: automated-pr
          delete-branch: true

